### ISSUE TITLE
Error when runing test_script.py.

### ISSUE THREAD

**Issue by 22881916** [Pendulibrium/ai-visual-storytelling-seq2seq#40]
When I have trained the model and then run test_script.py, the error occured. Could you please help me?
 I am using tensorflow 1.4, python 2.7.14 and Keras 2.15.

> /Users/ray/anaconda2/envs/tensorflow/bin/python /Users/ray/Desktop/ai-visual-storytelling-seq2seq-master/test_script.py
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/Users/ray/Desktop/ai-visual-storytelling-seq2seq-master/test_script.py", line 21, in <module>
>     include_sentence_encoder=True)
> TypeError: build_encoder_decoder_inference_from_file() takes at least 3 arguments (3 given)
> 
> Process finished with exit code 1
> 

![image](https://user-images.githubusercontent.com/8149167/38419601-ab156c22-39d3-11e8-8a53-c74481f30a7c.png)

**Comment by msmilevski** [comment]
Well the build_encoder_decoder_inference_from_file function is not finished yet. For now, it doesn't work when you use AttentionGRU for the decoder. We are still working on it.

**Comment by msmilevski** [comment]
There have been made too many changes to the code, and i can't explain the whole procedure here, but if you browse the repository at commit 84048c849795c5cc8e79de1700663bd3300977fd, you will find a workable solution.
