### ISSUE TITLE
TypeError: build_encoder_decoder_inference_from_file() takes at least 3 arguments (3 given)

### ISSUE THREAD

**Issue by 22881916** [Pendulibrium/ai-visual-storytelling-seq2seq#41]
Hello，
Emmmm, I used the repository at commit 84048c8, but there is still a mistake when I run test.script.py. It bothers me a long time, and I can't figure it out.

> /Users/ray/anaconda2/envs/tensorflow/bin/python /Users/ray/Downloads/ai-visual-storytelling-seq2seq-84048c849795c5cc8e79de1700663bd3300977fd/test_script.py
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/Users/ray/Downloads/ai-visual-storytelling-seq2seq-84048c849795c5cc8e79de1700663bd3300977fd/test_script.py", line 21, in <module>
>     include_sentence_encoder=True)
> TypeError: build_encoder_decoder_inference_from_file() takes at least 3 arguments (3 given)
> 
> Process finished with exit code 1
> 

![image](https://user-images.githubusercontent.com/8149167/38552663-6c772158-3cef-11e8-9e9a-417d02ee6088.png)

**Comment by msmilevski** [comment]
You need three parameters when calling the function. If you set include_sentnce_encoder=True, you also need to pass an instance from the class SentenceEncoderRNN. See inference_model.py for reference.

**Comment by 22881916** [comment]
I have tried this before, but there is another error.
ValueError: Error when checking : expected input_2 to have shape (22,) but got array with shape (1,)

>  /Users/ray/anaconda2/envs/tensorflow/bin/python /Users/ray/Downloads/ai-visual-storytelling-seq2seq-84048c849795c5cc8e79de1700663bd3300977fd/test_script.py
> Using TensorFlow backend.
> 2018-04-10 19:00:30.028812: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> ('encoder inputs shape: ', TensorShape([Dimension(None), Dimension(None), Dimension(4096)]))
> ('num: ', 2)
> Traceback (most recent call last):
>   File "/Users/ray/Downloads/ai-visual-storytelling-seq2seq-84048c849795c5cc8e79de1700663bd3300977fd/test_script.py", line 36, in <module>
>     image_embeddings = im_model.predict([image_encoder_data, encoder_batch_sentence_input_data[0]])
>   File "/Users/ray/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1817, in predict
>     check_batch_axis=False)
>   File "/Users/ray/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
>     str(data_shape))
> ValueError: Error when checking : expected input_2 to have shape (22,) but got array with shape (1,)
> 
> Process finished with exit code 1

**Comment by 22881916** [comment]
And when I changed such as this:
from:
>   image_encoder_data = image_encoder_data.reshape((1, image_encoder_data.shape[0], image_encoder_data.shape[1]))

to:
>   image_encoder_data = image_encoder_data.reshape((22, image_encoder_data.shape[0], image_encoder_data.shape[1]))

Another error ocurrs.

> /Users/ray/anaconda2/envs/tensorflow/bin/python /Users/ray/Downloads/ai-visual-storytelling-seq2seq-84048c849795c5cc8e79de1700663bd3300977fd/test_script.py
> Using TensorFlow backend.
> 2018-04-10 19:09:08.815837: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> ('encoder inputs shape: ', TensorShape([Dimension(None), Dimension(None), Dimension(4096)]))
> ('num: ', 2)
> Traceback (most recent call last):
>   File "/Users/ray/Downloads/ai-visual-storytelling-seq2seq-84048c849795c5cc8e79de1700663bd3300977fd/test_script.py", line 35, in <module>
>     image_encoder_data = image_encoder_data.reshape((22, image_encoder_data.shape[0], image_encoder_data.shape[1]))
> ValueError: cannot reshape array of size 20480 into shape (22,5,4096)
> 
> Process finished with exit code 1

![image](https://user-images.githubusercontent.com/8149167/38553787-f49620e0-3cf2-11e8-9066-a546553d37ca.png)
